publishDir = "docs"
# baseURL = 'https://aardwolverine.github.io/consultancy-site'
baseURL = 'https://acadsys.com.au'
languageCode = 'en-us'

title = "Academic Systems Consulting"
theme = "quint"

[params]
numImages = 10
css = ["css/custom.css"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

enableGitIbfo = true

[frontmatter]
  lastmod = ['lastmod', ':git', 'publishDate', 'date']
